export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://fewfound.co';
export const SITE_NAME = 'Few Found';
export const SITE_TAGLINE = "India's trust layer for marketing service providers.";
export const WHATSAPP = process.env.NEXT_PUBLIC_WHATSAPP || '919999999999';

export const CITIES = [
  { name: 'Mumbai',    slug: 'mumbai',    state: 'Maharashtra' },
  { name: 'Delhi',     slug: 'delhi',     state: 'Delhi'       },
  { name: 'Bengaluru', slug: 'bengaluru', state: 'Karnataka'   },
  { name: 'Hyderabad', slug: 'hyderabad', state: 'Telangana'   },
  { name: 'Chennai',   slug: 'chennai',   state: 'Tamil Nadu'  },
  { name: 'Pune',      slug: 'pune',      state: 'Maharashtra' },
  { name: 'Kolkata',   slug: 'kolkata',   state: 'West Bengal' },
  { name: 'Ahmedabad', slug: 'ahmedabad', state: 'Gujarat'     },
  { name: 'Jaipur',    slug: 'jaipur',    state: 'Rajasthan'   },
  { name: 'Gurugram',  slug: 'gurugram',  state: 'Haryana'     },
  { name: 'Noida',     slug: 'noida',     state: 'Uttar Pradesh'},
  { name: 'Chandigarh',slug: 'chandigarh',state: 'Punjab'      },
];

export const AGENCY_CATEGORIES = [
  { name: 'Performance Marketing',        slug: 'performance-marketing'   },
  { name: 'Paid Search',                  slug: 'paid-search'             },
  { name: 'Paid Social',                  slug: 'paid-social'             },
  { name: 'Programmatic Advertising',     slug: 'programmatic'            },
  { name: 'Affiliate Marketing',          slug: 'affiliate-marketing'     },
  { name: 'App Marketing & UA',           slug: 'app-marketing'           },
  { name: 'Creative & Branding',          slug: 'creative-branding'       },
  { name: 'Brand Strategy',               slug: 'brand-strategy'          },
  { name: 'Campaign Creative',            slug: 'campaign-creative'       },
  { name: 'Social Media Marketing',       slug: 'social-media'            },
  { name: 'Community Management',         slug: 'community-management'    },
  { name: 'Social Commerce',              slug: 'social-commerce'         },
  { name: 'PR & Communications',          slug: 'pr-communications'       },
  { name: 'Media Relations',              slug: 'media-relations'         },
  { name: 'Crisis Communications',        slug: 'crisis-communications'   },
  { name: 'Media Planning & Buying',      slug: 'media-planning'          },
  { name: 'TV Media Buying',              slug: 'tv-buying'               },
  { name: 'OOH & DOOH',                   slug: 'ooh-dooh'                },
  { name: 'Content Marketing',            slug: 'content-marketing'       },
  { name: 'SEO & Organic',                slug: 'seo-organic'             },
  { name: 'Technical SEO',                slug: 'technical-seo'           },
  { name: 'Link Building',                slug: 'link-building'           },
  { name: 'Influencer Marketing',         slug: 'influencer-marketing'    },
  { name: 'Creator Commerce',             slug: 'creator-commerce'        },
  { name: 'UGC Campaigns',                slug: 'ugc-campaigns'           },
  { name: 'Event & Experiential',         slug: 'event-experiential'      },
  { name: 'Brand Activations',            slug: 'brand-activations'       },
  { name: 'Trade Shows & Exhibitions',    slug: 'trade-shows'             },
  { name: 'B2B Marketing',                slug: 'b2b-marketing'           },
  { name: 'Account Based Marketing',      slug: 'account-based-marketing' },
  { name: 'Demand Generation',            slug: 'demand-generation'       },
  { name: 'Lead Generation',              slug: 'lead-generation'         },
  { name: 'Martech Implementation',       slug: 'martech'                 },
  { name: 'CRM Setup',                    slug: 'crm-setup'               },
  { name: 'Marketing Automation',         slug: 'marketing-automation'    },
  { name: 'Data & Analytics',             slug: 'data-analytics'          },
  { name: 'E-commerce Marketing',         slug: 'ecommerce-marketing'     },
  { name: 'D2C Growth',                   slug: 'd2c-growth'              },
  { name: 'Marketplace Marketing',        slug: 'marketplace-marketing'   },
  { name: 'Quick Commerce Marketing',     slug: 'quick-commerce'          },
  { name: 'Rural & Bharat Marketing',     slug: 'rural-marketing'         },
  { name: 'Regional Language Marketing',  slug: 'regional-marketing'      },
  { name: 'Vernacular Content',           slug: 'vernacular-content'      },
  { name: 'Startup Marketing',            slug: 'startup-marketing'       },
  { name: 'Healthcare Marketing',         slug: 'healthcare-marketing'    },
  { name: 'Pharma Marketing',             slug: 'pharma-marketing'        },
  { name: 'Real Estate Marketing',        slug: 'real-estate-marketing'   },
  { name: 'Automotive Marketing',         slug: 'automotive-marketing'    },
  { name: 'Financial Services Marketing', slug: 'financial-marketing'     },
  { name: 'EdTech Marketing',             slug: 'edtech-marketing'        },
  { name: 'Sports Marketing',             slug: 'sports-marketing'        },
  { name: 'Luxury Marketing',             slug: 'luxury-marketing'        },
  { name: 'Sustainability Marketing',     slug: 'sustainability-marketing' },
  { name: 'Cause Marketing',              slug: 'cause-marketing'         },
  { name: 'Political Campaigns',          slug: 'political-campaigns'     },
  { name: 'Government Communications',    slug: 'govt-communications'     },
  { name: 'Shopper & Trade Marketing',    slug: 'shopper-marketing'       },
  { name: 'Channel & Partner Marketing',  slug: 'channel-marketing'       },
  { name: 'Loyalty & Retention',          slug: 'loyalty-retention'       },
  { name: 'Referral Marketing',           slug: 'referral-marketing'      },
  { name: 'DSP / SSP Platforms',          slug: 'dsp-ssp'                 },
  { name: 'Customer Data Platforms (CDP)',slug: 'cdp'                     },
  { name: 'Attribution & MMP',            slug: 'attribution-mmp'         },
  { name: 'Ad Fraud Detection',           slug: 'ad-fraud'                },
  { name: 'Brand Safety Tools',           slug: 'brand-safety'            },
  { name: 'Social Listening Platforms',   slug: 'social-listening'        },
  { name: 'Retail Media Networks',        slug: 'retail-media'            },
  { name: 'CTV & OTT Advertising',        slug: 'ctv-ott'                 },
  { name: 'Gaming & Esports Marketing',   slug: 'gaming-esports'          },
];

export const CREATOR_CATEGORIES = [
  { name: 'Instagram  -  Fashion & Style',          slug: 'instagram-fashion'    },
  { name: 'Instagram  -  Beauty & Skincare',        slug: 'instagram-beauty'     },
  { name: 'Instagram  -  Food & Recipes',           slug: 'instagram-food'       },
  { name: 'Instagram  -  Travel & Lifestyle',       slug: 'instagram-travel'     },
  { name: 'Instagram  -  Personal Finance',         slug: 'instagram-finance'    },
  { name: 'Instagram  -  Tech & Gadgets',           slug: 'instagram-tech'       },
  { name: 'Instagram  -  Fitness & Wellness',       slug: 'instagram-fitness'    },
  { name: 'Instagram  -  Business & Startup',       slug: 'instagram-business'   },
  { name: 'Instagram  -  Education',                slug: 'instagram-education'  },
  { name: 'Instagram  -  Comedy & Entertainment',   slug: 'instagram-comedy'     },
  { name: 'Instagram  -  Regional & Vernacular',    slug: 'instagram-regional'   },
  { name: 'YouTube  -  Tech Reviews',               slug: 'youtube-tech'         },
  { name: 'YouTube  -  Personal Finance',           slug: 'youtube-finance'      },
  { name: 'YouTube  -  Food & Cooking',             slug: 'youtube-food'         },
  { name: 'YouTube  -  Gaming & Esports',           slug: 'youtube-gaming'       },
  { name: 'YouTube  -  Education & Explainers',     slug: 'youtube-education'    },
  { name: 'YouTube  -  Travel & Vlogs',             slug: 'youtube-travel'       },
  { name: 'YouTube  -  Business & Startup',         slug: 'youtube-business'     },
  { name: 'YouTube  -  Regional Language',          slug: 'youtube-regional'     },
  { name: 'LinkedIn  -  Marketing & Advertising',   slug: 'linkedin-marketing'   },
  { name: 'LinkedIn  -  Startup & Entrepreneurship',slug: 'linkedin-startup'     },
  { name: 'LinkedIn  -  Finance & Investment',      slug: 'linkedin-finance'     },
  { name: 'LinkedIn  -  HR & People',               slug: 'linkedin-hr'          },
  { name: 'LinkedIn  -  Technology & Product',      slug: 'linkedin-tech'        },
  { name: 'LinkedIn  -  Sales & BD',                slug: 'linkedin-sales'       },
  { name: 'Podcast  -  Business & Entrepreneurship',slug: 'podcast-business'     },
  { name: 'Podcast  -  Personal Finance',           slug: 'podcast-finance'      },
  { name: 'Podcast  -  Technology',                 slug: 'podcast-tech'         },
  { name: 'Podcast  -  Marketing & Advertising',    slug: 'podcast-marketing'    },
  { name: 'Podcast  -  True Crime',                 slug: 'podcast-truecrime'    },
  { name: 'Podcast  -  Health & Wellness',          slug: 'podcast-health'       },
  { name: 'Short-form Video  -  Reels & Shorts',    slug: 'shortform-video'      },
  { name: 'Newsletter Creator',                   slug: 'newsletter'           },
  { name: 'Twitter / X Influencer',               slug: 'twitter-x'            },
  { name: 'WhatsApp Community Creator',           slug: 'whatsapp-community'   },
  { name: 'Meme & Entertainment Accounts',        slug: 'meme-entertainment'   },
];

export const PROFESSIONAL_CATEGORIES = [
  { name: 'Fractional CMO',                    slug: 'fractional-cmo'          },
  { name: 'Fractional Chief Brand Officer',    slug: 'fractional-cbo'          },
  { name: 'Marketing Consultant',              slug: 'marketing-consultant'    },
  { name: 'Brand Strategist',                  slug: 'brand-strategist'        },
  { name: 'Go-to-Market Specialist',           slug: 'gtm-specialist'          },
  { name: 'Growth Advisor',                    slug: 'growth-advisor'          },
  { name: 'Performance Marketing Consultant',  slug: 'performance-consultant'  },
  { name: 'SEO Consultant',                    slug: 'seo-consultant'          },
  { name: 'Content Strategist',               slug: 'content-strategist'      },
  { name: 'CRO Specialist',                   slug: 'cro-specialist'          },
  { name: 'MarTech Consultant',               slug: 'martech-consultant'      },
  { name: 'Marketing Analyst',                slug: 'marketing-analyst'       },
  { name: 'Independent Media Planner',        slug: 'media-planner'           },
  { name: 'PR Consultant',                    slug: 'pr-consultant'           },
  { name: 'Influencer Marketing Consultant',  slug: 'influencer-consultant'   },
  { name: 'B2B Marketing Specialist',         slug: 'b2b-specialist'          },
  { name: 'Interim Marketing Director',       slug: 'interim-director'        },
  { name: 'Startup Marketing Advisor',        slug: 'startup-advisor'         },
  { name: 'Freelance Creative Director',      slug: 'creative-director'       },
  { name: 'Freelance Copywriter',             slug: 'copywriter'              },
  { name: 'Brand Naming Consultant',          slug: 'brand-naming'            },
  { name: 'Packaging Design Consultant',      slug: 'packaging-design'        },
  { name: 'Rural Marketing Specialist',       slug: 'rural-specialist'        },
  { name: 'Vernacular Marketing Specialist',  slug: 'vernacular-specialist'   },
  { name: 'Sports Marketing Consultant',      slug: 'sports-consultant'       },
  { name: 'Luxury Marketing Consultant',      slug: 'luxury-consultant'       },
  { name: 'Customer Experience Consultant',   slug: 'cx-consultant'           },
  { name: 'Marketing Trainer & Coach',        slug: 'marketing-trainer'       },
];

export const BRAND_INDUSTRIES = [
  'D2C / Direct to Consumer',
  'FMCG',
  'Fashion & Apparel',
  'Beauty & Personal Care',
  'Food & Beverage',
  'Consumer Tech',
  'FinTech',
  'EdTech',
  'HealthTech',
  'SaaS / B2B Software',
  'E-commerce & Marketplace',
  'Quick Commerce',
  'Gaming & Esports',
  'Real Estate',
  'Automotive',
  'Travel & Hospitality',
  'Healthcare & Hospital',
  'Pharma',
  'Financial Services & Insurance',
  'Media & Entertainment',
  'OTT / Streaming',
  'Retail Chain',
  'Restaurant & QSR',
  'NGO & Non-profit',
  'Government & PSU',
  'Startup (Pre-revenue)',
  'Startup (Revenue stage)',
  'B2B / Enterprise',
  'Manufacturing',
  'Infrastructure',
];

export const TEAM_SIZES = ['1-5','6-10','10-25','25-50','50-100','100+'];

export const PRICING = {
  agency_verification:     24999,
  creator_verification:    14999,
  professional_verification: 24999,
  brand_verification:      14999,
  brand_membership_connect: 60000,
  brand_membership_full:   150000,
};
